version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: rass-opensearch
    environment:
      - cluster.name=rass-cluster
      - node.name=rass-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - rass-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: rass-opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    networks:
      - rass-network

  rass-api:
    build: .
    container_name: rass-api
    ports:
      - "3000:3000"
    environment:
      - RASS_BACKEND=opensearch
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_INDEX=rass-documents
      - HOST=0.0.0.0
      - PORT=3000
      - LOG_LEVEL=info
    depends_on:
      - opensearch
    networks:
      - rass-network

volumes:
  opensearch-data:

networks:
  rass-network:
    driver: bridge