name: Deploy RASS API

on:
  push:
    branches: [ main ]
  create:
  delete:

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y sshpass jq

      - uses: maxklema/proxmox-launchpad@v0.0.7
        with:
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          github_pat: ${{ secrets.GH_PAT }}

  manage-container:
    runs-on: self-hosted
    needs: setup-runner
    steps:
      - uses: maxklema/proxmox-launchpad@v0.0.7
        with:
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
          github_pat: ${{ secrets.GH_PAT }}
          http_port: 3000
          services: '["docker"]'
          root_start_command: docker-compose up -d
          container_env_vars: '{"RASS_BACKEND": "opensearch", "OPENSEARCH_URL": "http://opensearch:9200", "OPENSEARCH_INDEX": "rass-documents", "HOST": "0.0.0.0", "PORT": "3000", "LOG_LEVEL": "info"}'
